import express, { Request, Response } from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { PrismaClient } from '@prisma/client';
import multer from 'multer';
import path from 'path';
import fs from 'fs';
import { Resend } from 'resend';
import crypto from 'crypto';

dotenv.config();

const app = express();
const prisma = new PrismaClient();
const PORT = process.env.PORT || 5000;

const resend = new Resend(process.env.RESEND_API_KEY);

const uploadDir = path.join(__dirname, '../uploads');
if (!fs.existsSync(uploadDir)) fs.mkdirSync(uploadDir);

app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ limit: '10mb', extended: true }));
app.use(cors({ origin: "*", methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"] }));

// Serve uploads from both possible paths
app.use('/uploads', express.static(uploadDir));
app.use('/server/uploads', express.static(uploadDir));

// IMPORTANT: Render's default filesystem is ephemeral. Store new blog images in
// Cloudinary instead of writing them to server/uploads, so images survive restarts,
// deploys, and free-service spin-downs. Multer keeps the file in memory only long
// enough to send it to Cloudinary.
const storage = multer.memoryStorage();
const upload = multer({
  storage,
  limits: { fileSize: 10 * 1024 * 1024 },
  fileFilter: (_req, file, cb) => {
    const allowed = ['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif'];
    cb(null, allowed.includes(file.mimetype));
  },
});

function createCloudinarySignature(params: Record<string, string | number>): string {
  const payload = Object.keys(params)
    .sort()
    .map((key) => `${key}=${params[key]}`)
    .join('&');

  const secret = process.env.CLOUDINARY_API_SECRET;
  if (!secret) {
    throw new Error('CLOUDINARY_API_SECRET is not configured');
  }

  return crypto.createHash('sha1').update(payload + secret).digest('hex');
}

async function uploadImageToCloudinary(file: Express.Multer.File): Promise<string> {
  const cloudName = process.env.CLOUDINARY_CLOUD_NAME;
  const apiKey = process.env.CLOUDINARY_API_KEY;
  const apiSecret = process.env.CLOUDINARY_API_SECRET;
  const folder = process.env.CLOUDINARY_FOLDER || 'name-change-expert/blogs';

  if (!cloudName || !apiKey || !apiSecret) {
    throw new Error(
      'Cloudinary is not configured. Set CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, and CLOUDINARY_API_SECRET.'
    );
  }

  const timestamp = Math.floor(Date.now() / 1000);
  const signature = createCloudinarySignature({ folder, timestamp });
  const base64File = `data:${file.mimetype};base64,${file.buffer.toString('base64')}`;

  const form = new FormData();
  form.append('file', base64File);
  form.append('api_key', apiKey);
  form.append('timestamp', String(timestamp));
  form.append('folder', folder);
  form.append('signature', signature);

  const response = await fetch(`https://api.cloudinary.com/v1_1/${cloudName}/image/upload`, {
    method: 'POST',
    body: form,
  });

  const data = await response.json() as { secure_url?: string; error?: { message?: string } };

  if (!response.ok || !data.secure_url) {
    throw new Error(data.error?.message || 'Cloudinary image upload failed');
  }

  return data.secure_url;
}

// Decode HTML entities that may have been stored by an older version of the editor.
// Example: &lt;h1&gt;Heading&lt;/h1&gt; -> <h1>Heading</h1>
function decodeHtmlEntities(input: string = ""): string {
  const namedEntities: Record<string, string> = {
    amp: "&",
    lt: "<",
    gt: ">",
    quot: '"',
    apos: "'",
    nbsp: "\u00a0",
  };

  let output = input;

  // Decode a few times to also repair double-encoded values such as &amp;lt;h1&amp;gt;.
  for (let pass = 0; pass < 3; pass += 1) {
    const decoded = output.replace(/&(#x?[0-9a-f]+|[a-z]+);/gi, (full, entity) => {
      const lower = String(entity).toLowerCase();

      if (lower.startsWith("#x")) {
        const codePoint = Number.parseInt(lower.slice(2), 16);
        return Number.isFinite(codePoint) ? String.fromCodePoint(codePoint) : full;
      }

      if (lower.startsWith("#")) {
        const codePoint = Number.parseInt(lower.slice(1), 10);
        return Number.isFinite(codePoint) ? String.fromCodePoint(codePoint) : full;
      }

      return namedEntities[lower] ?? full;
    });

    if (decoded === output) break;
    output = decoded;
  }

  return output;
}

// Allow only the formatting generated by the admin visual editor.
// This keeps headings, paragraphs, links and text colors while blocking scripts/event handlers.
function sanitizeBlogHtml(input: string = ""): string {
  const decodedInput = decodeHtmlEntities(input);

  return decodedInput
    .replace(/<\s*(script|style|iframe|object|embed|form|input|button|textarea|select|option)[^>]*>[\s\S]*?<\s*\/\s*\1\s*>/gi, "")
    .replace(/<\s*(script|style|iframe|object|embed|form|input|button|textarea|select|option)[^>]*\/?\s*>/gi, "")
    .replace(/\s+on[a-z]+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi, "")
    .replace(/\s+(src|href)\s*=\s*("|')\s*javascript:[\s\S]*?\2/gi, "")
    .replace(/\s+(src|href)\s*=\s*javascript:[^\s>]+/gi, "")
    .replace(/\s+style\s*=\s*("|')([\s\S]*?)\1/gi, (_match, quote, style) => {
      const safeColor = String(style).match(/(?:^|;)\s*color\s*:\s*(#[0-9a-f]{3,8}|rgb\([^)]*\)|rgba\([^)]*\)|[a-z]+)\s*(?:;|$)/i);
      return safeColor ? ` style="color: ${safeColor[1]}"` : "";
    })
    .replace(/<\/?(?!\/?(?:p|br|h1|h2|h3|h4|h5|h6|strong|b|em|i|u|s|ul|ol|li|a|blockquote|div|span)\b)[^>]+>/gi, "");
}

// ==========================================
// 🚀 MASTER API ROUTER
// ==========================================
const apiRouter = express.Router();

apiRouter.post('/contact', async (req: Request, res: Response): Promise<void> => {
  try {
    const { name, phone, email, service, message } = req.body;
    const newLead = await prisma.contactMessage.create({
      data: { name, phone, email: email || "N/A", service, message: message || "" },
    });

    const { data, error } = await resend.emails.send({
      from: 'onboarding@resend.dev',
      to: 'info@namechangeexpert.in',
      subject: `🚨 New Lead: ${name} | ${service}`,
      html: `
        <h2>New Lead Received!</h2>
        <p><strong>Name:</strong> ${name}</p>
        <p><strong>Phone:</strong> ${phone}</p>
        <p><strong>Email:</strong> ${email || 'N/A'}</p>
        <p><strong>Service:</strong> ${service}</p>
        <p><strong>Message:</strong> ${message || 'No additional message.'}</p>
      `
    });

    if (error) {
      console.error("Resend Error:", error);
      res.status(500).json({ status: 'error', message: error.message });
      return; 
    }

    res.status(201).json({ status: 'success', data: newLead });
  } catch (error) {
    console.error("Database Error:", error);
    res.status(500).json({ status: 'error', message: 'Internal server error' });
  }
});

apiRouter.get('/contact', async (req: Request, res: Response): Promise<void> => {
  try {
    const leads = await prisma.contactMessage.findMany({ orderBy: { createdAt: 'desc' } });
    res.status(200).json(leads);
  } catch (error) {
    res.status(500).json({ status: 'error', message: 'Internal server error' });
  }
});


apiRouter.post('/blogs', upload.single('cover_image'), async (req: Request, res: Response): Promise<void> => {
  try {
    const { title, excerpt, author, slug } = req.body;
    const safeExcerpt = sanitizeBlogHtml(excerpt);
    const imageUrl = req.file ? await uploadImageToCloudinary(req.file) : '';
    const newBlog = await prisma.blogPost.create({
      data: { title, excerpt: safeExcerpt, cover_image: imageUrl, author, slug },
    });
    res.status(201).json({ status: 'success', data: newBlog });
  } catch (error) {
    console.error('Create blog error:', error);
    res.status(500).json({ status: 'error', message: error instanceof Error ? error.message : 'Server error' });
  }
});

apiRouter.get('/blogs', async (req: Request, res: Response): Promise<void> => {
  const blogs = await prisma.blogPost.findMany({ orderBy: { publishedAt: 'desc' } });
  // Repair older posts that were saved as escaped HTML and sanitize them before sending to the browser.
  const safeBlogs = blogs.map((blog) => ({
    ...blog,
    excerpt: sanitizeBlogHtml(blog.excerpt),
  }));
  res.status(200).json(safeBlogs);
});

apiRouter.put('/blogs/:id', upload.single('cover_image'), async (req: Request, res: Response): Promise<void> => {
  try {
    const id = String(req.params.id);
    const { title, excerpt, author, slug } = req.body;
    const safeExcerpt = sanitizeBlogHtml(excerpt);
    const existingBlog = await prisma.blogPost.findUnique({ where: { id } });
    if (!existingBlog) { res.status(404).json({ message: 'Blog not found' }); return; }

    const imageUrl = req.file ? await uploadImageToCloudinary(req.file) : existingBlog.cover_image;
    const updatedBlog = await prisma.blogPost.update({
      where: { id },
      data: { title, excerpt: safeExcerpt, author, slug, cover_image: imageUrl },
    });
    res.status(200).json({ status: 'success', data: updatedBlog });
  } catch (error) {
    console.error('Update blog error:', error);
    res.status(500).json({ status: 'error', message: error instanceof Error ? error.message : 'Failed to update' });
  }
});

apiRouter.delete('/blogs/:id', async (req: Request, res: Response): Promise<void> => {
  try {
    await prisma.blogPost.delete({ where: { id: String(req.params.id) } });
    res.status(200).json({ status: 'success', message: 'Deleted' });
  } catch (error) {
    res.status(500).json({ status: 'error', message: 'Failed to delete' });
  }
});

// ==========================================
// 🛡️ THE MAGIC TRICK: Bind to both paths
// ==========================================
app.use('/api', apiRouter);
app.use('/server/api', apiRouter);

app.listen(PORT, () => {
  console.log(`🚀 Server running on port ${PORT}`);
});